version: "3.8"

services:
  app:
    container_name: battleships-modern-js
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app:delegated
      - /app/node_modules
